"""Scoring constants and thresholds for adjustment pair detection."""

SCORE_EXACT_AMOUNT = 40
SCORE_SAME_CARD = 25
SCORE_SAME_PERSON = 10
SCORE_REFUND_KEYWORD = 20
SCORE_HIGH_MERCHANT_SIMILARITY = 20
SCORE_MEDIUM_MERCHANT_SIMILARITY = 10
SCORE_SMALL_DATE_GAP = 10
SCORE_MEDIUM_DATE_GAP = 5

PENALTY_PERSON_CONFLICT = -15
PENALTY_MERCHANT_MISMATCH = -20
PENALTY_LARGE_AMOUNT_DELTA = -25

CONFIDENCE_HIGH_THRESHOLD = 70
CONFIDENCE_MEDIUM_THRESHOLD = 45

PARTIAL_REFUND_PERCENT_THRESHOLD = 10.0
PARTIAL_REFUND_MIN_MERCHANT_SIMILARITY = 0.6

DATE_GAP_SMALL = 7
DATE_GAP_MEDIUM = 30

MERCHANT_SIMILARITY_HIGH = 0.7
MERCHANT_SIMILARITY_MEDIUM = 0.4

REFUND_KEYWORDS = {
    "REFUND",
    "REVERSAL",
    "REVERSED",
    "REFUNDED",
    "CREDIT BALANCE REFUND",
}

PAYMENT_KEYWORDS = {
    "PAYMENT RECEIVED",
    "PAYMENT - THANK YOU",
    "NEFT",
    "IMPS",
    "UPI",
    "BILLPAY",
    "AUTOPAY",
}

PROCESSOR_WRAPPERS = {
    "REFUND FRM",
    "REFUND FROM",
    "RAZORPAY PAYMENTS",
    "RAZORPAY",
    "GATEWAY",
    "PG ",
    "PAYMENT GATEWAY",
}

COSMETIC_WORDING = {
    "REFUND",
    "REVERSAL",
    "REVERSED",
    "PAY IN EMIS",
    "EMI",
}

__all__ = [
    "CONFIDENCE_HIGH_THRESHOLD",
    "CONFIDENCE_MEDIUM_THRESHOLD",
    "COSMETIC_WORDING",
    "DATE_GAP_MEDIUM",
    "DATE_GAP_SMALL",
    "MERCHANT_SIMILARITY_HIGH",
    "MERCHANT_SIMILARITY_MEDIUM",
    "PARTIAL_REFUND_MIN_MERCHANT_SIMILARITY",
    "PARTIAL_REFUND_PERCENT_THRESHOLD",
    "PAYMENT_KEYWORDS",
    "PENALTY_LARGE_AMOUNT_DELTA",
    "PENALTY_MERCHANT_MISMATCH",
    "PENALTY_PERSON_CONFLICT",
    "PROCESSOR_WRAPPERS",
    "REFUND_KEYWORDS",
    "SCORE_EXACT_AMOUNT",
    "SCORE_HIGH_MERCHANT_SIMILARITY",
    "SCORE_MEDIUM_DATE_GAP",
    "SCORE_MEDIUM_MERCHANT_SIMILARITY",
    "SCORE_REFUND_KEYWORD",
    "SCORE_SAME_CARD",
    "SCORE_SAME_PERSON",
    "SCORE_SMALL_DATE_GAP",
]
