"""Scoring constants and thresholds for adjustment pair detection."""

# Signal point values for scoring
SCORE_EXACT_AMOUNT = 40
SCORE_SAME_CARD = 25
SCORE_SAME_PERSON = 10
SCORE_REFUND_KEYWORD = 20
SCORE_HIGH_MERCHANT_SIMILARITY = 20
SCORE_MEDIUM_MERCHANT_SIMILARITY = 10
SCORE_SMALL_DATE_GAP = 10
SCORE_MEDIUM_DATE_GAP = 5

# Negative signals
PENALTY_PERSON_CONFLICT = -15
PENALTY_MERCHANT_MISMATCH = -20
PENALTY_LARGE_AMOUNT_DELTA = -25

# Confidence thresholds
CONFIDENCE_HIGH_THRESHOLD = 70
CONFIDENCE_MEDIUM_THRESHOLD = 45

# Partial refund thresholds
PARTIAL_REFUND_PERCENT_THRESHOLD = 10.0  # <= 10%
PARTIAL_REFUND_MIN_MERCHANT_SIMILARITY = 0.6

# Date gap scoring thresholds (in days)
DATE_GAP_SMALL = 7
DATE_GAP_MEDIUM = 30

# Merchant similarity thresholds
MERCHANT_SIMILARITY_HIGH = 0.7
MERCHANT_SIMILARITY_MEDIUM = 0.4

# Refund keywords (credit side)
REFUND_KEYWORDS = {
    "REFUND",
    "REVERSAL",
    "REVERSED",
    "REFUNDED",
    "CREDIT BALANCE REFUND",
}

# Payment keywords (for detecting normal payments)
PAYMENT_KEYWORDS = {
    "PAYMENT RECEIVED",
    "PAYMENT - THANK YOU",
    "NEFT",
    "IMPS",
    "UPI",
    "BILLPAY",
    "AUTOPAY",
}

# Processor wrappers to strip
PROCESSOR_WRAPPERS = {
    "REFUND FRM",
    "REFUND FROM",
    "RAZORPAY PAYMENTS",
    "RAZORPAY",
    "GATEWAY",
    "PG ",
    "PAYMENT GATEWAY",
}

# Cosmetic wording to strip
COSMETIC_WORDING = {
    "REFUND",
    "REVERSAL",
    "REVERSED",
    "PAY IN EMIS",
    "EMI",
}

__all__ = [
    "SCORE_EXACT_AMOUNT",
    "SCORE_SAME_CARD",
    "SCORE_SAME_PERSON",
    "SCORE_REFUND_KEYWORD",
    "SCORE_HIGH_MERCHANT_SIMILARITY",
    "SCORE_MEDIUM_MERCHANT_SIMILARITY",
    "SCORE_SMALL_DATE_GAP",
    "SCORE_MEDIUM_DATE_GAP",
    "PENALTY_PERSON_CONFLICT",
    "PENALTY_MERCHANT_MISMATCH",
    "PENALTY_LARGE_AMOUNT_DELTA",
    "CONFIDENCE_HIGH_THRESHOLD",
    "CONFIDENCE_MEDIUM_THRESHOLD",
    "PARTIAL_REFUND_PERCENT_THRESHOLD",
    "PARTIAL_REFUND_MIN_MERCHANT_SIMILARITY",
    "DATE_GAP_SMALL",
    "DATE_GAP_MEDIUM",
    "MERCHANT_SIMILARITY_HIGH",
    "MERCHANT_SIMILARITY_MEDIUM",
    "REFUND_KEYWORDS",
    "PAYMENT_KEYWORDS",
    "PROCESSOR_WRAPPERS",
    "COSMETIC_WORDING",
]
